[theme]
primaryColor = "#7b1fa2"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1e1e2f"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
